# Generated by Django 5.2.6 on 2025-09-28 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPokemon',
            fields=[
                ('id_tipo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pokemon', models.IntegerField()),
                ('favorito', models.BooleanField(default=False)),
                ('em_grupo', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'id_pokemon')},
            },
        ),
    ]
